//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashison_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
