//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashison_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int PurchaseOrderId { get; set; }
        public int ShipperId { get; set; }
        public string Status { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
