//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashison_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertype_quyen
    {
        public int usertype_id { get; set; }
        public string quyen_id { get; set; }
        public string GhiChu { get; set; }
    
        public virtual User User { get; set; }
    }
}
