//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashison_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Shop
    {
        public int Store_ID { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ShopName { get; set; }
        public string Decription { get; set; }
        public string Pictures { get; set; }
        public string Coverpics { get; set; }
    }
}
