//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public string Order_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Store_ID { get; set; }
        public Nullable<double> delivery { get; set; }
        public string payment { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string status { get; set; }
        public string decription { get; set; }
        public Nullable<int> Address_ID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
    }
}
