//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Cancel
    {
        public string Name { get; set; }
        public string Order_ID { get; set; }
        public Nullable<double> delivery { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> status { get; set; }
        public string decription { get; set; }
        public string address { get; set; }
        public Nullable<double> Total_Order { get; set; }
    }
}
